replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

mongodb:
  image: mongo:6.0
  username: root
  password: example
  replicaSet: rs0
  port: 27017

web:
  image: dockermanhuli/webkub:latest
  port: 3000

serviceAccount:
  create: true
  name: mongo-serviceaccount  

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: myapp.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - myapp.local
      secretName: myapp-tls
