apiVersion: v1
kind: Namespace
metadata:
  name: mongodb-namespace
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-keyfile
  namespace: mongodb-namespace
type: Opaque
data:
  # Base64-kodiertes Keyfile; vor Einsatz anpassen (echo -n "your-keyfile-content" | base64)
  mongo-keyfile: bXlTZWNyZXRLZXk=
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: mongodb-namespace
spec:
  serviceName: "mongo"
  replicas: 3
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: mongo
          image: mongo:6.0
          command:
            - mongod
            - "--replSet"
            - "rs0"
            - "--keyFile"
            - /etc/secrets/mongo-keyfile
            - "--bind_ip_all"
          ports:
            - containerPort: 27017
              name: mongo
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
            - name: keyfile
              mountPath: /etc/secrets
              readOnly: true
      volumes:
        - name: keyfile
          secret:
            secretName: mongo-keyfile
  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: mongodb-namespace
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongo
