apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo3
  name: mongo3
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo3
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/mongo-net: "true"
        io.kompose.service: mongo3
    spec:
      containers:
        - args:
            - mongod
            - --replSet
            - rs0
            - --keyFile
            - /data/mongo-keyfile
          image: mongo:6.0
          name: mongo3
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: mongo3-data
            - mountPath: /data/mongo-keyfile
              name: mongo3-claim1
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: mongo3-data
          persistentVolumeClaim:
            claimName: mongo3-data
        - name: mongo3-claim1
          persistentVolumeClaim:
            claimName: mongo3-claim1
            readOnly: true
status: {}
