apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo1
  name: mongo1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/mongo-net: "true"
        io.kompose.service: mongo1
    spec:
      containers:
        - args:
            - mongod
            - --replSet
            - rs0
            - --keyFile
            - /data/mongo-keyfile
          env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
          image: mongo:6.0
          name: mongo1
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: mongo1-data
            - mountPath: /data/mongo-keyfile
              name: mongo1-claim1
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: mongo1-data
          persistentVolumeClaim:
            claimName: mongo1-data
        - name: mongo1-claim1
          persistentVolumeClaim:
            claimName: mongo1-claim1
            readOnly: true
status: {}
