apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-init
  name: mongo-init
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo-init
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/mongo-net: "true"
        io.kompose.service: mongo-init
    spec:
      containers:
        - command:
            - bash
            - /init-replica.sh
          image: mongo:6.0
          name: mongo-init
          resources: {}
          volumeMounts:
            - mountPath: /init-replica.sh
              name: mongo-init-claim0
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: mongo-init-claim0
          persistentVolumeClaim:
            claimName: mongo-init-claim0
            readOnly: true
status: {}
